version: '2'

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24



services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        networks:
            frontend:
                ipv4_address: 172.20.0.5
        ports:
            - "8087:6000"
        
    db:
        image: mongo:3.6.1
        container_name: db
        networks:
            frontend:
                ipv4_address: 172.20.0.6
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
        
volumes:
    mongodb:
    mongodb_config:
