orbs:
  maven: circleci/maven@1.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test: 
          test_results_path: /TALLER-DE-DE-MODULARIZACI-N-CON-VIRTUALIZACI-N-E-INTRODUCCI-N-A-DOCKER-Y-A-AWS/Tarea/LogService

          
       
