version: 2.1

orbs:
  maven:  circleci/maven@0.0.12
jobs: 
  test: 
    docker:
      - image: buildpack-deps:trusty
    steps: 
               
      - run:
          name: TestLogService
          command: |
            git clone https://github.com/davinchicoronado/TALLER-DE-DE-MODULARIZACI-N-CON-VIRTUALIZACI-N-E-INTRODUCCI-N-A-DOCKER-Y-A-AWS.git 
            cd  TALLER-DE-DE-MODULARIZACI-N-CON-VIRTUALIZACI-N-E-INTRODUCCI-N-A-DOCKER-Y-A-AWS/Tarea/LogService
            echo $(pwd)
            mvn compile
            
      
workflows:
  maven_test:
    jobs:
      - test

          
       
