version: 2.1

orbs:
  maven: circleci/maven@1.1
jobs: 
  test: 
    docker:
      - image: buildpack-deps:trusty
    steps:       
      - run: git clone https://github.com/davinchicoronado/TALLER-DE-DE-MODULARIZACI-N-CON-VIRTUALIZACI-N-E-INTRODUCCI-N-A-DOCKER-Y-A-AWS.git           
      - run: ls -La
      - run: cd  TALLER-DE-DE-MODULARIZACI-N-CON-VIRTUALIZACI-N-E-INTRODUCCI-N-A-DOCKER-Y-A-AWS 
      - run: cd  TALLER-DE-DE-MODULARIZACI-N-CON-VIRTUALIZACI-N-E-INTRODUCCI-N-A-DOCKER-Y-A-AWS
      - run: ls -La
      - run: echo $(pwd)
      - run: echo $(ls)

workflows:
  maven_test:
    jobs:
      - test
