version: 2.1
parameters:
  app_src_directory:
    default: ""
    description: /home/circleci/project/Tareas/LogService
    type: string
orbs:
  maven:  circleci/maven@0.0.12
workflows:
  maven_test:
    jobs:
      - maven/test

          
       
