version: '2'
networks:
  logservice_frontend:
    external: true

services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web2
        ports:
            - "8088:6001"
        
        networks:
            logservice_frontend:
                ipv4_address: 172.20.0.7        
        
        